# Generated by Django 6.1 on 2026-09-01 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='System', max_length=150)),
                ('action', models.CharField(max_length=100)),
                ('entity_type', models.CharField(default='System', max_length=100)),
                ('entity_id', models.IntegerField(blank=True, null=True)),
                ('details', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
